namespace CM.EDITAR.Templates;

/// <summary>
/// CM.EDITAR+ comprehensive ShellNew extension catalog — single source of truth
/// for both the C# Windows app and the React mockup (via tools/generate-catalog.mjs).
///
/// Each row uses the same fixed positional shape so the Node generator script
/// can regex-parse it line-by-line. Cross-listing the same extension under
/// multiple categories is intentional (e.g. .dwg in CAD/3D and Omega Database).
///
/// Risk policy:
///   - high: extensions that execute on double-click on Windows
///           (.exe .bat .cmd .com .ps1 .vbs .wsf .crx .msi .pif .sys .scr .hta .apk .llamafile)
///           — always shipped disabled.
///   - warn: shell/scripting on non-Windows hosts (.sh .bash .zsh .fish .ksh .csh .ahk),
///           model binaries that can deserialize/run code (.pkl .pickle .ckpt .pt .pth
///           .gguf .ggml .safetensors .onnx .ort .nemo .h5 .hdf5 .keras .pb .tflite
///           .trt .engine .vae .lora .clip .dduf .index .model .t5x), most archives,
///           legacy/binary blobs.
///   - rec : data/text/media/source files that are inert at create time.
/// </summary>
public static class ExtensionCatalog
{
    public sealed record Entry(
        string Ext,
        string Label,
        string Category,
        string State,    // "enabled" | "disabled" | "missing"
        string Risk,     // "rec" | "warn" | "high"
        string Pack,
        string? Template,
        string Description);

    /// <summary>The 11 wired top-level categories that drive the sidebar.</summary>
    public static readonly string[] Categories = new[]
    {
        "AI/Automation",
        "Archives",
        "CAD/3D",
        "Cloud Docs",
        "Legacy",
        "Media",
        "Office/Docs",
        "Omega Database",
        "Power User",
        "System",
        "Text/Data",
    };

    public static readonly IReadOnlyList<Entry> All = new Entry[]
    {
        // === Text/Data ===
        new(".txt", "Text Document", "Text/Data", "enabled", "rec", "system", null, "Empty UTF-8 text file."),
        new(".md", "Markdown Document", "Text/Data", "enabled", "rec", "cm-editar.core", "frontmatter.md", "Markdown note with YAML front-matter scaffold."),
        new(".markdown", "Markdown Document (alt)", "Text/Data", "enabled", "rec", "system", null, "Alternate Markdown extension."),
        new(".rtf", "Rich Text Document", "Text/Data", "enabled", "rec", "system", null, "Rich Text Format file."),
        new(".csv", "CSV Spreadsheet", "Text/Data", "enabled", "rec", "cm-editar.core", "headers.csv", "Comma-separated values."),
        new(".tsv", "TSV File", "Text/Data", "enabled", "rec", "system", null, "Tab-separated values."),
        new(".log", "Log File", "Text/Data", "enabled", "rec", "system", null, "Plain log file."),
        new(".nfo", "NFO File", "Text/Data", "enabled", "rec", "system", null, "Info text file."),
        new(".readme", "README File", "Text/Data", "enabled", "rec", "system", null, "README text file."),
        new(".reg", "Registry Script", "Text/Data", "disabled", "warn", "system", null, "Windows registry import script."),
        new(".ini", "INI File", "Text/Data", "enabled", "rec", "system", null, "Plain-text init file."),
        new(".cfg", "Config File", "Text/Data", "enabled", "rec", "system", null, "Generic config file."),
        new(".conf", "Conf File", "Text/Data", "enabled", "rec", "system", null, "Generic configuration."),
        new(".properties", "Properties File", "Text/Data", "enabled", "rec", "system", null, "Java-style properties file."),
        new(".xml", "XML Document", "Text/Data", "enabled", "rec", "system", null, "XML document."),
        new(".wpd", "WordPerfect Document", "Text/Data", "missing", "warn", "third-party", null, "WordPerfect document."),
        new(".wps", "Works Document", "Text/Data", "missing", "warn", "third-party", null, "Microsoft Works document."),
        new(".org", "Org-Mode Document", "Text/Data", "enabled", "rec", "system", null, "Emacs Org-mode document."),
        new(".rst", "reStructuredText", "Text/Data", "enabled", "rec", "system", null, "reStructuredText document."),
        new(".tex", "LaTeX Source", "Text/Data", "enabled", "rec", "third-party", null, "LaTeX document source."),
        new(".msg", "Outlook Message", "Text/Data", "missing", "warn", "office", null, "Outlook mail message."),
        new(".inf", "Windows Setup INF", "Text/Data", "enabled", "rec", "system", null, "Windows setup info file."),
        new(".ins", "Internet Settings", "Text/Data", "enabled", "rec", "system", null, "Legacy internet settings file."),
        new(".ebook", "E-Book Source", "Text/Data", "enabled", "rec", "third-party", null, "Generic e-book text source."),

        // === Office/Docs ===
        new(".accdb", "Microsoft Access Database", "Office/Docs", "missing", "warn", "office", null, "Access database (Office)."),
        new(".doc", "Microsoft Word 97-2003", "Office/Docs", "enabled", "rec", "office", null, "Word 97-2003 document."),
        new(".docx", "Microsoft Word Document", "Office/Docs", "enabled", "rec", "office", "blank.docx", "Blank Word 2007+ document."),
        new(".dot", "Word 97-2003 Template", "Office/Docs", "enabled", "rec", "office", null, "Word 97-2003 template."),
        new(".dotx", "Word Template", "Office/Docs", "enabled", "rec", "office", null, "Word 2007+ template."),
        new(".kpr", "KDE Slideshow", "Office/Docs", "enabled", "rec", "third-party", null, "KDE slideshow file."),
        new(".mdb", "Access 97-2003", "Office/Docs", "missing", "warn", "office", null, "Access 97-2003 database."),
        new(".mpp", "Microsoft Project", "Office/Docs", "missing", "warn", "office", null, "Project document."),
        new(".odp", "OpenDocument Presentation", "Office/Docs", "enabled", "rec", "office", null, "OpenDocument presentation."),
        new(".ods", "OpenDocument Spreadsheet", "Office/Docs", "enabled", "rec", "office", null, "OpenDocument spreadsheet."),
        new(".odt", "OpenDocument Text", "Office/Docs", "enabled", "rec", "office", null, "OpenDocument text."),
        new(".one", "OneNote Section", "Office/Docs", "missing", "warn", "office", null, "OneNote section file."),
        new(".pdf", "PDF Document", "Office/Docs", "enabled", "rec", "system", null, "PDF document."),
        new(".ppsx", "PowerPoint Show", "Office/Docs", "missing", "warn", "office", null, "PowerPoint show."),
        new(".ppt", "PowerPoint 97-2003", "Office/Docs", "missing", "warn", "office", null, "PowerPoint 97-2003."),
        new(".pptx", "PowerPoint Presentation", "Office/Docs", "missing", "warn", "office", null, "PowerPoint 2007+ presentation."),
        new(".pub", "Publisher Document", "Office/Docs", "missing", "warn", "office", null, "Publisher document."),
        new(".vsd", "Visio Drawing", "Office/Docs", "missing", "warn", "office", null, "Visio 97-2003 drawing."),
        new(".vsdx", "Visio Drawing", "Office/Docs", "missing", "warn", "office", null, "Visio 2013+ drawing."),
        new(".xls", "Excel 97-2003", "Office/Docs", "missing", "warn", "office", null, "Excel 97-2003 worksheet."),
        new(".xltx", "Excel Template", "Office/Docs", "missing", "warn", "office", null, "Excel template."),
        new(".xlsm", "Excel Macro Workbook", "Office/Docs", "missing", "warn", "office", null, "Excel macro-enabled workbook."),
        new(".xlsx", "Excel Worksheet", "Office/Docs", "missing", "warn", "office", null, "Excel 2007+ worksheet."),

        // === Cloud Docs ===
        new(".gdoc", "Google Docs", "Cloud Docs", "disabled", "rec", "cloud", null, "Google Docs cloud document."),
        new(".gdraw", "Google Drawing", "Cloud Docs", "disabled", "rec", "cloud", null, "Google Drawing."),
        new(".gform", "Google Form", "Cloud Docs", "disabled", "rec", "cloud", null, "Google Form."),
        new(".gsheet", "Google Sheets", "Cloud Docs", "disabled", "rec", "cloud", null, "Google Sheets."),
        new(".gslides", "Google Slides", "Cloud Docs", "disabled", "rec", "cloud", null, "Google Slides."),
        new(".kcb", "Kindle Project", "Cloud Docs", "disabled", "rec", "cloud", null, "Kindle Create project."),
        new(".key", "Apple Keynote", "Cloud Docs", "disabled", "rec", "cloud", null, "Apple Keynote presentation."),
        new(".key-tef", "iCloud Keynote", "Cloud Docs", "disabled", "rec", "cloud", null, "iCloud-optimized Keynote file."),
        new(".keynote", "Apple Keynote (alt)", "Cloud Docs", "disabled", "rec", "cloud", null, "Apple Keynote presentation."),
        new(".numbers", "Apple Numbers", "Cloud Docs", "disabled", "rec", "cloud", null, "Apple Numbers spreadsheet."),
        new(".pages", "Apple Pages", "Cloud Docs", "disabled", "rec", "cloud", null, "Apple Pages document."),
        new(".ical", "iCalendar (Apple)", "Cloud Docs", "disabled", "rec", "cloud", null, "Apple iCalendar file."),
        new(".ics", "Calendar Event", "Cloud Docs", "enabled", "rec", "system", null, "Calendar event/iCalendar file."),

        // === Archives ===
        new(".zip", "ZIP Archive", "Archives", "enabled", "rec", "system", null, "Empty ZIP container (built-in)."),
        new(".7z", "7-Zip Archive", "Archives", "missing", "warn", "third-party", null, "7-Zip archive."),
        new(".bz2", "BZip2 Archive", "Archives", "disabled", "warn", "third-party", null, "Bzip2-compressed file."),
        new(".cab", "Windows Cabinet", "Archives", "enabled", "rec", "system", null, "Windows cabinet archive."),
        new(".gz", "GZip Archive", "Archives", "disabled", "warn", "third-party", null, "Gzip-compressed file."),
        new(".iso", "ISO Disc Image", "Archives", "disabled", "warn", "system", null, "ISO disc image."),
        new(".pea", "PeaZip PEA", "Archives", "disabled", "warn", "third-party", null, "PeaZip PEA archive."),
        new(".rar", "WinRAR Archive", "Archives", "missing", "warn", "third-party", null, "WinRAR archive."),
        new(".tar", "TAR Archive", "Archives", "disabled", "warn", "third-party", null, "TAR archive."),
        new(".xz", "XZ Archive", "Archives", "disabled", "warn", "third-party", null, "XZ-compressed file."),
        new(".zipx", "Extended ZIP", "Archives", "disabled", "warn", "third-party", null, "WinZip extended ZIP."),
        new(".zst", "Zstandard Archive", "Archives", "disabled", "warn", "third-party", null, "Zstandard-compressed file."),
        new(".a", "Unix Archive", "Archives", "disabled", "warn", "third-party", null, "Unix ar archive."),
        new(".aar", "Android Library Archive", "Archives", "disabled", "warn", "third-party", null, "Android AAR library."),
        new(".apk", "Android Package", "Archives", "disabled", "high", "third-party", null, "Android installable package."),
        new(".ar", "Unix Archive", "Archives", "disabled", "warn", "third-party", null, "Unix ar archive."),
        new(".br", "Brotli Archive", "Archives", "disabled", "warn", "third-party", null, "Brotli-compressed file."),
        new(".cpio", "cpio Archive", "Archives", "disabled", "warn", "third-party", null, "cpio archive."),
        new(".deb", "Debian Package", "Archives", "disabled", "warn", "third-party", null, "Debian package archive."),
        new(".dmg", "Apple Disk Image", "Archives", "disabled", "warn", "third-party", null, "Apple disk image."),
        new(".egg", "Python Egg", "Archives", "disabled", "warn", "third-party", null, "Python egg distribution."),
        new(".jar", "Java Archive", "Archives", "disabled", "warn", "third-party", null, "Java archive."),
        new(".lha", "LHA Archive", "Archives", "disabled", "warn", "third-party", null, "LHA archive."),
        new(".lz", "Lzip Archive", "Archives", "disabled", "warn", "third-party", null, "Lzip-compressed file."),
        new(".lz4", "LZ4 Archive", "Archives", "disabled", "warn", "third-party", null, "LZ4-compressed file."),
        new(".lzma", "LZMA Archive", "Archives", "disabled", "warn", "third-party", null, "LZMA-compressed file."),
        new(".lzo", "LZO Archive", "Archives", "disabled", "warn", "third-party", null, "LZO-compressed file."),
        new(".mar", "Mozilla Archive", "Archives", "disabled", "warn", "third-party", null, "Mozilla archive."),
        new(".pak", "Game Pak Archive", "Archives", "disabled", "warn", "third-party", null, "Game pak/data archive."),
        new(".rpm", "RedHat Package", "Archives", "disabled", "warn", "third-party", null, "RedHat package."),
        new(".s7z", "7-Zip Multi-Volume", "Archives", "disabled", "warn", "third-party", null, "7-Zip multi-volume archive."),
        new(".shar", "Shell Archive", "Archives", "disabled", "warn", "third-party", null, "Shell self-extracting archive."),
        new(".tbz2", "Tar+BZip2", "Archives", "disabled", "warn", "third-party", null, "Tar wrapped in bzip2."),
        new(".tgz", "Tar+GZip", "Archives", "disabled", "warn", "third-party", null, "Tar wrapped in gzip."),
        new(".tlz", "Tar+LZMA", "Archives", "disabled", "warn", "third-party", null, "Tar wrapped in lzma."),
        new(".txz", "Tar+XZ", "Archives", "disabled", "warn", "third-party", null, "Tar wrapped in xz."),
        new(".war", "Java Web Archive", "Archives", "disabled", "warn", "third-party", null, "Java web app archive."),
        new(".whl", "Python Wheel", "Archives", "disabled", "warn", "third-party", null, "Python wheel distribution."),
        new(".xpi", "Mozilla Extension", "Archives", "disabled", "warn", "third-party", null, "Mozilla browser extension."),
        new(".winzip", "Windows ZIP (legacy)", "Archives", "disabled", "warn", "system", null, "Legacy WinZip-style archive."),

        // === CAD/3D ===
        new(".dwg", "AutoCAD Drawing", "CAD/3D", "disabled", "rec", "third-party", null, "AutoCAD drawing."),
        new(".dxf", "DXF Drawing", "CAD/3D", "disabled", "rec", "third-party", null, "DXF interchange drawing."),
        new(".f3d", "Fusion 360 Design", "CAD/3D", "disabled", "rec", "third-party", null, "Fusion 360 design."),
        new(".g", "G-Code (CAD)", "CAD/3D", "disabled", "rec", "third-party", null, "Generic G-code/CNC file."),
        new(".gcode", "G-Code", "CAD/3D", "disabled", "rec", "third-party", null, "CNC/3D-print G-code."),
        new(".iam", "Inventor Assembly", "CAD/3D", "missing", "warn", "third-party", null, "Inventor assembly."),
        new(".ifc", "IFC BIM Model", "CAD/3D", "disabled", "rec", "third-party", null, "IFC building model."),
        new(".iges", "IGES 3D Model", "CAD/3D", "disabled", "rec", "third-party", null, "IGES 3D model."),
        new(".igs", "IGES 3D Model", "CAD/3D", "disabled", "rec", "third-party", null, "IGES 3D model (alt)."),
        new(".ipt", "Inventor Part", "CAD/3D", "missing", "warn", "third-party", null, "Inventor part."),
        new(".max", "3ds Max Scene", "CAD/3D", "missing", "warn", "third-party", null, "3ds Max scene file."),
        new(".rvt", "Revit Project", "CAD/3D", "missing", "warn", "third-party", null, "Revit project."),
        new(".skp", "SketchUp Model", "CAD/3D", "disabled", "rec", "third-party", null, "SketchUp model."),
        new(".sldasm", "SolidWorks Assembly", "CAD/3D", "missing", "warn", "third-party", null, "SolidWorks assembly."),
        new(".sldprt", "SolidWorks Part", "CAD/3D", "missing", "warn", "third-party", null, "SolidWorks part."),
        new(".step", "STEP 3D Model", "CAD/3D", "disabled", "rec", "third-party", null, "STEP 3D model."),
        new(".stp", "STEP 3D Model", "CAD/3D", "disabled", "rec", "third-party", null, "STEP 3D model (alt)."),
        new(".3ds", "3D Studio Scene", "CAD/3D", "disabled", "rec", "third-party", null, "Autodesk 3D Studio scene."),
        new(".3mf", "3D Manufacturing", "CAD/3D", "disabled", "rec", "third-party", null, "3MF print model."),
        new(".smt", "Siemens 3D Model", "CAD/3D", "disabled", "rec", "third-party", null, "Siemens NX 3D model."),
        new(".stl", "STL 3D Model", "CAD/3D", "disabled", "rec", "third-party", null, "Stereolithography 3D model."),
        new(".obj", "Wavefront OBJ", "CAD/3D", "disabled", "rec", "third-party", null, "Wavefront OBJ 3D model."),
        new(".scad", "OpenSCAD Source", "CAD/3D", "enabled", "rec", "third-party", null, "OpenSCAD parametric source."),
        new(".fbx", "Autodesk FBX", "CAD/3D", "disabled", "rec", "third-party", null, "Autodesk FBX 3D model."),
        new(".dae", "Collada 3D", "CAD/3D", "disabled", "rec", "third-party", null, "Collada digital asset exchange."),
        new(".glb", "glTF Binary", "CAD/3D", "disabled", "rec", "third-party", null, "glTF binary 3D asset."),
        new(".gltf", "glTF JSON", "CAD/3D", "disabled", "rec", "third-party", null, "glTF JSON 3D asset."),

        // === Legacy ===
        new(".bat", "Batch File", "Legacy", "disabled", "high", "system", null, "DOS batch — executes on double-click."),
        new(".bin", "Binary File", "Legacy", "disabled", "warn", "system", null, "Generic binary blob."),
        new(".com", "DOS COM Executable", "Legacy", "disabled", "high", "system", null, "Legacy DOS COM executable."),
        new(".dbf", "dBase Database", "Legacy", "disabled", "warn", "system", null, "dBase legacy database."),
        new(".ebcdic", "EBCDIC Data", "Legacy", "disabled", "warn", "system", null, "Mainframe EBCDIC data."),
        new(".fox", "FoxPro File", "Legacy", "disabled", "warn", "system", null, "Visual FoxPro file."),
        new(".hqx", "BinHex Archive", "Legacy", "disabled", "warn", "system", null, "Mac BinHex archive."),
        new(".ima", "Floppy Disk Image", "Legacy", "disabled", "warn", "system", null, "Legacy floppy disk image."),
        new(".img", "Disk Image", "Legacy", "disabled", "warn", "system", null, "Generic raw disk image."),
        new(".imz", "Zipped Disk Image", "Legacy", "disabled", "warn", "system", null, "Zipped disk image."),
        new(".isz", "Zipped ISO", "Legacy", "disabled", "warn", "system", null, "Zipped ISO image."),
        new(".jcl", "IBM JCL Script", "Legacy", "disabled", "warn", "system", null, "IBM job control language."),
        new(".pif", "Program Info File", "Legacy", "disabled", "high", "system", null, "Program information file (executes)."),
        new(".sit", "StuffIt Archive", "Legacy", "disabled", "warn", "system", null, "Mac StuffIt archive."),
        new(".sys", "Windows System File", "Legacy", "disabled", "high", "system", null, "Windows system driver/file."),
        new(".scr", "Screen Saver Executable", "Legacy", "disabled", "high", "system", null, "Windows screen saver — executes on double-click."),
        new(".hta", "HTML Application", "Legacy", "disabled", "high", "system", null, "HTML Application — runs scripts with full trust."),

        // === Media ===
        new(".ai", "Adobe Illustrator", "Media", "disabled", "rec", "third-party", null, "Adobe Illustrator file."),
        new(".als", "Ableton Live Set", "Media", "disabled", "rec", "third-party", null, "Ableton Live set."),
        new(".braw", "Blackmagic RAW", "Media", "disabled", "rec", "third-party", null, "Blackmagic RAW video."),
        new(".eml", "Email Message", "Media", "enabled", "rec", "system", null, "Generic email message."),
        new(".eps", "EPS Image", "Media", "disabled", "rec", "third-party", null, "Encapsulated PostScript."),
        new(".gif", "GIF Image", "Media", "enabled", "rec", "system", null, "GIF image."),
        new(".icns", "macOS Icon", "Media", "disabled", "rec", "third-party", null, "macOS icon."),
        new(".ico", "Windows Icon", "Media", "enabled", "rec", "system", null, "Windows icon file."),
        new(".iff", "IFF Container", "Media", "disabled", "rec", "third-party", null, "Interchange File Format."),
        new(".jpg", "JPEG Image", "Media", "enabled", "rec", "system", null, "JPEG image."),
        new(".jpeg", "JPEG Image (alt)", "Media", "enabled", "rec", "system", null, "JPEG image (alt)."),
        new(".hdr", "HDR Image", "Media", "disabled", "rec", "third-party", null, "High-dynamic-range image."),
        new(".mid", "MIDI File", "Media", "enabled", "rec", "system", null, "MIDI music file."),
        new(".mod", "Module Audio", "Media", "disabled", "rec", "third-party", null, "Tracker/module audio."),
        new(".mp3", "MP3 Audio", "Media", "enabled", "rec", "system", null, "MP3 audio."),
        new(".mp4", "MP4 Video", "Media", "enabled", "rec", "system", null, "MP4 video."),
        new(".png", "PNG Image", "Media", "enabled", "rec", "system", null, "PNG image."),
        new(".svg", "SVG Image", "Media", "enabled", "rec", "system", null, "Scalable vector graphic."),
        new(".tif", "TIFF Image", "Media", "enabled", "rec", "system", null, "TIFF image."),
        new(".tiff", "TIFF Image (alt)", "Media", "enabled", "rec", "system", null, "TIFF image (alt)."),
        new(".wav", "WAV Audio", "Media", "enabled", "rec", "system", null, "WAV audio."),
        new(".webm", "WebM Video", "Media", "enabled", "rec", "system", null, "WebM video."),
        new(".webp", "WebP Image", "Media", "enabled", "rec", "system", null, "WebP image."),
        new(".bmp", "Bitmap Image", "Media", "enabled", "rec", "system", null, "Windows bitmap."),
        new(".heic", "HEIC Image", "Media", "enabled", "rec", "system", null, "HEIC photo."),
        new(".heif", "HEIF Image", "Media", "enabled", "rec", "system", null, "HEIF photo."),
        new(".avif", "AVIF Image", "Media", "enabled", "rec", "system", null, "AVIF image."),
        new(".jxl", "JPEG XL Image", "Media", "enabled", "rec", "system", null, "JPEG XL image."),
        new(".psd", "Photoshop Document", "Media", "disabled", "rec", "third-party", null, "Adobe Photoshop document."),
        new(".xcf", "GIMP Image", "Media", "disabled", "rec", "third-party", null, "GIMP image."),
        new(".tga", "Targa Image", "Media", "disabled", "rec", "third-party", null, "Targa image."),
        new(".yuv", "Raw YUV Video", "Media", "disabled", "rec", "system", null, "Raw YUV media data."),
        new(".flac", "FLAC Audio", "Media", "enabled", "rec", "system", null, "FLAC lossless audio."),
        new(".aac", "AAC Audio", "Media", "enabled", "rec", "system", null, "AAC audio."),
        new(".opus", "Opus Audio", "Media", "enabled", "rec", "system", null, "Opus audio."),
        new(".ogg", "OGG Audio", "Media", "enabled", "rec", "system", null, "Ogg Vorbis audio."),
        new(".wma", "WMA Audio", "Media", "enabled", "rec", "system", null, "Windows Media Audio."),
        new(".m4a", "M4A Audio", "Media", "enabled", "rec", "system", null, "M4A audio."),
        new(".mov", "QuickTime Movie", "Media", "enabled", "rec", "system", null, "QuickTime movie."),
        new(".mkv", "Matroska Video", "Media", "enabled", "rec", "system", null, "Matroska video."),
        new(".avi", "AVI Video", "Media", "enabled", "rec", "system", null, "AVI video."),
        new(".flv", "Flash Video", "Media", "enabled", "rec", "system", null, "Flash video."),
        new(".wmv", "Windows Media Video", "Media", "enabled", "rec", "system", null, "Windows Media video."),
        new(".3g2", "3GPP2 Video", "Media", "enabled", "rec", "system", null, "3GPP2 mobile video."),
        new(".3gp", "3GPP Video", "Media", "enabled", "rec", "system", null, "3GPP mobile video."),
        new(".m4v", "iTunes Video", "Media", "enabled", "rec", "system", null, "M4V video."),
        new(".mpeg", "MPEG Video", "Media", "enabled", "rec", "system", null, "MPEG video."),
        new(".mpg", "MPEG Video", "Media", "enabled", "rec", "system", null, "MPEG video (alt)."),
        new(".vob", "DVD Video Object", "Media", "enabled", "rec", "system", null, "DVD video object."),
        new(".ape", "Monkey's Audio", "Media", "disabled", "rec", "third-party", null, "Monkey's Audio."),
        new(".aiff", "AIFF Audio", "Media", "enabled", "rec", "system", null, "AIFF audio."),
        new(".gpx", "GPS Exchange", "Media", "disabled", "rec", "third-party", null, "GPS exchange file."),
        new(".kml", "Keyhole Markup", "Media", "disabled", "rec", "third-party", null, "Keyhole markup language."),
        new(".kmz", "Keyhole Zipped", "Media", "disabled", "rec", "third-party", null, "Zipped Keyhole markup."),
        new(".dds", "DirectDraw Surface", "Media", "disabled", "rec", "third-party", null, "DirectDraw surface texture."),
        new(".thm", "Thumbnail", "Media", "enabled", "rec", "system", null, "Camera thumbnail."),

        // === Omega Database ===
        new(".astro", "Astro Component", "Omega Database", "enabled", "rec", "third-party", null, "Astro component."),
        new(".avsc", "Avro Schema", "Omega Database", "enabled", "rec", "third-party", null, "Avro schema."),
        new(".bak", "Backup File", "Omega Database", "enabled", "rec", "system", null, "Generic backup file."),
        new(".bashrc", "Bash RC", "Omega Database", "enabled", "rec", "third-party", null, "Bash startup file."),
        new(".bicep", "Azure Bicep", "Omega Database", "enabled", "rec", "third-party", null, "Azure Bicep template."),
        new(".blend", "Blender Project", "Omega Database", "disabled", "rec", "third-party", null, "Blender project."),
        new(".cjs", "CommonJS Module", "Omega Database", "enabled", "rec", "third-party", null, "CommonJS JavaScript."),
        new(".cmake", "CMake Script", "Omega Database", "enabled", "rec", "third-party", null, "CMake build script."),
        new(".cmd", "Windows Command Script", "Omega Database", "disabled", "high", "system", null, "Windows command script — executes."),
        new(".cron", "Cron Schedule", "Omega Database", "enabled", "rec", "third-party", null, "Cron schedule file."),
        new(".crt", "Certificate File", "Omega Database", "enabled", "rec", "system", null, "X.509 certificate."),
        new(".crypt14", "WhatsApp DB Backup", "Omega Database", "disabled", "warn", "third-party", null, "WhatsApp encrypted DB backup."),
        new(".dart", "Dart Source", "Omega Database", "enabled", "rec", "third-party", null, "Dart source."),
        new(".db", "Database File", "Omega Database", "disabled", "warn", "system", null, "Generic database file."),
        new(".dcm", "DICOM Image", "Omega Database", "disabled", "warn", "third-party", null, "DICOM medical image."),
        new(".edi", "EDI File", "Omega Database", "enabled", "rec", "third-party", null, "Electronic data interchange."),
        new(".ex", "Elixir Source", "Omega Database", "enabled", "rec", "third-party", null, "Elixir source."),
        new(".fasta", "FASTA Sequence", "Omega Database", "enabled", "rec", "third-party", null, "FASTA biology sequence."),
        new(".geo", "Gmsh Geo", "Omega Database", "enabled", "rec", "third-party", null, "Gmsh geometry file."),
        new(".gpg", "GPG Key", "Omega Database", "disabled", "warn", "system", null, "GPG key/data file."),
        new(".gradle", "Gradle Build", "Omega Database", "enabled", "rec", "third-party", null, "Gradle build script."),
        new(".graphql", "GraphQL Schema", "Omega Database", "enabled", "rec", "third-party", null, "GraphQL schema."),
        new(".glsl", "OpenGL Shader", "Omega Database", "enabled", "rec", "third-party", null, "OpenGL shader source."),
        new(".gts", "GNU TS Format", "Omega Database", "enabled", "rec", "third-party", null, "GNU triangulated surface."),
        new(".gr2", "Granny3D Model", "Omega Database", "disabled", "rec", "third-party", null, "Granny3D / Epic model."),
        new(".gmax", "GMax Scene", "Omega Database", "disabled", "rec", "third-party", null, "GMax scene file."),
        new(".hl7", "HL7 File", "Omega Database", "enabled", "rec", "third-party", null, "HL7 healthcare message."),
        new(".ib", "InterBase DB", "Omega Database", "disabled", "warn", "third-party", null, "InterBase DB file."),
        new(".ibd", "InnoDB Table", "Omega Database", "disabled", "warn", "third-party", null, "InnoDB table data."),
        new(".less", "LESS Stylesheet", "Omega Database", "enabled", "rec", "third-party", null, "LESS stylesheet."),
        new(".liquid", "Liquid Template", "Omega Database", "enabled", "rec", "third-party", null, "Liquid template."),
        new(".lnk", "Shortcut", "Omega Database", "disabled", "warn", "system", null, "Windows shortcut."),
        new(".lua", "Lua Script", "Omega Database", "enabled", "rec", "third-party", null, "Lua script."),
        new(".makefile", "Makefile", "Omega Database", "enabled", "rec", "third-party", null, "GNU make file."),
        new(".mdx", "MDX Document", "Omega Database", "enabled", "rec", "third-party", null, "MDX (Markdown + JSX)."),
        new(".mjs", "ES Module JS", "Omega Database", "enabled", "rec", "third-party", null, "ECMAScript module."),
        new(".ofx", "OFX Banking", "Omega Database", "enabled", "rec", "third-party", null, "OFX banking export."),
        new(".old", "Old File", "Omega Database", "enabled", "rec", "system", null, "Backup/old file marker."),
        new(".ovpn", "OpenVPN Config", "Omega Database", "enabled", "rec", "third-party", null, "OpenVPN config."),
        new(".parquet", "Parquet Data", "Omega Database", "enabled", "rec", "third-party", null, "Apache Parquet columnar data."),
        new(".pcap", "Packet Capture", "Omega Database", "disabled", "warn", "third-party", null, "Packet capture file."),
        new(".pem", "PEM Certificate", "Omega Database", "enabled", "rec", "system", null, "PEM-encoded certificate."),
        new(".php", "PHP Script", "Omega Database", "enabled", "rec", "third-party", null, "PHP script."),
        new(".pl", "Perl Script", "Omega Database", "enabled", "rec", "third-party", null, "Perl script."),
        new(".plist", "Apple plist", "Omega Database", "enabled", "rec", "third-party", null, "Apple property list."),
        new(".proto", "Protocol Buffers", "Omega Database", "enabled", "rec", "third-party", null, "Protocol Buffers schema."),
        new(".psd1", "PowerShell Data", "Omega Database", "disabled", "warn", "system", null, "PowerShell data file."),
        new(".psm1", "PowerShell Module", "Omega Database", "disabled", "warn", "system", null, "PowerShell module."),
        new(".qif", "Quicken Interchange", "Omega Database", "enabled", "rec", "third-party", null, "Quicken interchange file."),
        new(".rdp", "Remote Desktop", "Omega Database", "disabled", "warn", "system", null, "Remote desktop file."),
        new(".sb3", "Scratch 3 Project", "Omega Database", "disabled", "rec", "third-party", null, "Scratch 3.0 project."),
        new(".scss", "SCSS Stylesheet", "Omega Database", "enabled", "rec", "third-party", null, "Sass SCSS stylesheet."),
        new(".service", "systemd Service", "Omega Database", "enabled", "rec", "third-party", null, "systemd unit file."),
        new(".sqlite", "SQLite Database", "Omega Database", "disabled", "warn", "third-party", null, "SQLite database."),
        new(".svelte", "Svelte Component", "Omega Database", "enabled", "rec", "third-party", null, "Svelte component."),
        new(".tf", "Terraform File", "Omega Database", "enabled", "rec", "third-party", null, "Terraform config."),
        new(".tfvars", "Terraform Vars", "Omega Database", "enabled", "rec", "third-party", null, "Terraform variables."),
        new(".url", "Internet Shortcut", "Omega Database", "disabled", "warn", "system", null, "Internet shortcut."),
        new(".vbs", "VBScript", "Omega Database", "disabled", "high", "system", null, "VBScript — executes on double-click."),
        new(".vhd", "Virtual Hard Disk", "Omega Database", "disabled", "warn", "system", null, "VHD virtual disk."),
        new(".vhdx", "Hyper-V Virtual Disk", "Omega Database", "disabled", "warn", "system", null, "Hyper-V virtual disk."),
        new(".vue", "Vue Component", "Omega Database", "enabled", "rec", "third-party", null, "Vue.js component."),
        new(".wasm", "WebAssembly Binary", "Omega Database", "enabled", "rec", "third-party", null, "WebAssembly binary."),
        new(".webloc", "Web Location", "Omega Database", "disabled", "rec", "third-party", null, "Apple web location."),
        new(".wsf", "Windows Script File", "Omega Database", "disabled", "high", "system", null, "Windows Script File — executes."),
        new(".x12", "ANSI X12", "Omega Database", "enabled", "rec", "third-party", null, "ANSI X12 EDI file."),
        new(".xbrl", "XBRL Filing", "Omega Database", "enabled", "rec", "third-party", null, "XBRL business reporting filing."),
        new(".zshrc", "Zsh RC", "Omega Database", "enabled", "rec", "third-party", null, "Zsh startup file."),

        // === Power User (comprehensive Git/Dev) ===
        new(".app", "macOS App Bundle", "Power User", "disabled", "warn", "system", null, "macOS application bundle."),
        new(".c", "C Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "C source file."),
        new(".cpp", "C++ Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "C++ source file."),
        new(".cc", "C++ Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "C++ source (alt)."),
        new(".cxx", "C++ Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "C++ source (alt)."),
        new(".cs", "C# Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "C# source file."),
        new(".csproj", "C# Project", "Power User", "enabled", "rec", "cm-editar.dev", null, "C# project file."),
        new(".css", "CSS Stylesheet", "Power User", "enabled", "rec", "cm-editar.web", null, "CSS stylesheet."),
        new(".dockerfile", "Dockerfile", "Power User", "enabled", "rec", "cm-editar.dev", null, "Dockerfile."),
        new(".exe", "Windows Executable", "Power User", "disabled", "high", "system", null, "Windows executable — never auto-create."),
        new(".crx", "Chrome Extension", "Power User", "disabled", "high", "system", null, "Chrome browser extension package — never auto-create."),
        new(".html", "HTML5 Document", "Power User", "enabled", "rec", "cm-editar.web", "html5.html", "HTML5 document with boilerplate."),
        new(".htm", "HTML Document (alt)", "Power User", "enabled", "rec", "cm-editar.web", null, "HTML document (alt extension)."),
        new(".gs", "Google Apps Script", "Power User", "enabled", "rec", "cm-editar.dev", null, "Google Apps Script."),
        new(".js", "JavaScript", "Power User", "enabled", "rec", "cm-editar.web", null, "JavaScript source."),
        new(".json", "JSON Document", "Power User", "enabled", "rec", "cm-editar.core", "object.json", "JSON document."),
        new(".jsx", "React JSX", "Power User", "enabled", "rec", "cm-editar.web", null, "React JSX component."),
        new(".ksh", "Korn Shell Script", "Power User", "disabled", "warn", "cm-editar.dev", null, "Unix Korn shell script."),
        new(".msi", "Windows Installer", "Power User", "disabled", "high", "system", null, "Windows installer — never auto-create."),
        new(".pdb", "Program Database", "Power User", "disabled", "warn", "cm-editar.dev", null, "PDB debug symbols."),
        new(".ps1", "PowerShell Script", "Power User", "disabled", "high", "cm-editar.dev", null, "PowerShell script — execution policy applies."),
        new(".py", "Python Script", "Power User", "enabled", "warn", "cm-editar.dev", "main.py", "Python script with __main__ guard."),
        new(".sh", "Shell Script", "Power User", "disabled", "warn", "cm-editar.dev", null, "POSIX shell script."),
        new(".sln", "VS Solution", "Power User", "enabled", "rec", "cm-editar.dev", null, "Visual Studio solution."),
        new(".sql", "SQL Script", "Power User", "enabled", "rec", "cm-editar.dev", null, "SQL script."),
        new(".toml", "TOML Config", "Power User", "enabled", "rec", "cm-editar.dev", null, "TOML config."),
        new(".ts", "TypeScript", "Power User", "enabled", "rec", "cm-editar.web", null, "TypeScript source."),
        new(".tsx", "TypeScript React", "Power User", "enabled", "rec", "cm-editar.web", null, "TypeScript React component."),
        new(".yaml", "YAML File", "Power User", "enabled", "rec", "cm-editar.dev", null, "YAML config."),
        new(".yml", "YAML File (alt)", "Power User", "enabled", "rec", "cm-editar.dev", null, "YAML config (alt)."),
        new(".h", "C Header", "Power User", "enabled", "rec", "cm-editar.dev", null, "C header file."),
        new(".hh", "C++ Header", "Power User", "enabled", "rec", "cm-editar.dev", null, "C++ header (alt)."),
        new(".hpp", "C++ Header", "Power User", "enabled", "rec", "cm-editar.dev", null, "C++ header file."),
        new(".hxx", "C++ Header", "Power User", "enabled", "rec", "cm-editar.dev", null, "C++ header (alt)."),
        new(".go", "Go Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Go source file."),
        new(".rs", "Rust Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Rust source file."),
        new(".kt", "Kotlin Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Kotlin source file."),
        new(".kts", "Kotlin Script", "Power User", "enabled", "rec", "cm-editar.dev", null, "Kotlin script."),
        new(".swift", "Swift Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Swift source file."),
        new(".java", "Java Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Java source file."),
        new(".rb", "Ruby Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Ruby source file."),
        new(".lua", "Lua Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Lua source (Power User)."),
        new(".scala", "Scala Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Scala source file."),
        new(".dart", "Dart Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Dart source (Power User)."),
        new(".ex", "Elixir Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Elixir source (Power User)."),
        new(".vue", "Vue Component", "Power User", "enabled", "rec", "cm-editar.web", null, "Vue.js component (Power User)."),
        new(".svelte", "Svelte Component", "Power User", "enabled", "rec", "cm-editar.web", null, "Svelte component (Power User)."),
        new(".astro", "Astro Component", "Power User", "enabled", "rec", "cm-editar.web", null, "Astro component (Power User)."),
        new(".mdx", "MDX Document", "Power User", "enabled", "rec", "cm-editar.dev", null, "MDX document (Power User)."),
        new(".zig", "Zig Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Zig source file."),
        new(".nim", "Nim Source", "Power User", "enabled", "rec", "cm-editar.dev", null, "Nim source file."),
        new(".r", "R Script", "Power User", "enabled", "rec", "cm-editar.dev", null, "R source file."),
        new(".graphql", "GraphQL", "Power User", "enabled", "rec", "cm-editar.dev", null, "GraphQL schema/queries."),
        new(".proto", "Protocol Buffers", "Power User", "enabled", "rec", "cm-editar.dev", null, "Protocol Buffers schema."),
        new(".bash", "Bash Script", "Power User", "disabled", "warn", "cm-editar.dev", null, "Bash shell script."),
        new(".zsh", "Zsh Script", "Power User", "disabled", "warn", "cm-editar.dev", null, "Z shell script."),
        new(".fish", "Fish Script", "Power User", "disabled", "warn", "cm-editar.dev", null, "Fish shell script."),
        new(".cmake", "CMake Script", "Power User", "enabled", "rec", "cm-editar.dev", null, "CMake build script."),
        new(".gradle", "Gradle Build", "Power User", "enabled", "rec", "cm-editar.dev", null, "Gradle build script."),
        new(".bazel", "Bazel Build", "Power User", "enabled", "rec", "cm-editar.dev", null, "Bazel build file."),
        new(".vcxproj", "VC++ Project", "Power User", "enabled", "rec", "cm-editar.dev", null, "Visual C++ project."),
        new(".lock", "Lock File", "Power User", "enabled", "rec", "cm-editar.dev", null, "Package manager lock file."),
        new(".patch", "Patch File", "Power User", "enabled", "rec", "cm-editar.dev", null, "Unified patch file."),
        new(".diff", "Diff File", "Power User", "enabled", "rec", "cm-editar.dev", null, "Unified diff."),

        // === AI/Automation ===
        new(".ahk", "AutoHotkey Script", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "AutoHotkey automation script."),
        new(".arrow", "Arrow Dataset", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Apache Arrow dataset."),
        new(".chat", "Chat Transcript", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "AI chat transcript."),
        new(".ckpt", "Checkpoint Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Stable Diffusion / ML checkpoint."),
        new(".gguf", "GGUF Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "GGUF (llama.cpp) model."),
        new(".ipynb", "Jupyter Notebook", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Jupyter notebook."),
        new(".jinja", "Jinja Template", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Jinja template."),
        new(".jsonl", "JSON Lines", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "JSON Lines dataset."),
        new(".ndjson", "NDJSON", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Newline-delimited JSON."),
        new(".onnx", "ONNX Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "ONNX cross-framework model."),
        new(".prompt", "Prompt File", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Reusable prompt text."),
        new(".pt", "PyTorch Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "PyTorch model artifact."),
        new(".pth", "PyTorch Weights", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "PyTorch weights checkpoint."),
        new(".safetensors", "SafeTensors Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Hugging Face safetensors weights."),
        new(".workflow", "Workflow File", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Generic workflow definition."),
        new(".bpe", "BPE Tokenizer", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "BPE tokenizer model."),
        new(".chatml", "ChatML Prompt", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "ChatML prompt format."),
        new(".clip", "CLIP Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "CLIP image/text encoder model."),
        new(".cmfy", "ComfyUI Bundle", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "ComfyUI workflow bundle."),
        new(".diffusers", "Diffusers Marker", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Hugging Face Diffusers marker."),
        new(".dduf", "Diffusers DDUF", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Diffusers DDUF artifact."),
        new(".emb", "Embedding File", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Embedding/vector artifact."),
        new(".embedding", "Embedding Artifact", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Embedding artifact (alt)."),
        new(".eval", "Eval Spec", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "LLM eval spec."),
        new(".faiss", "FAISS Index", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "FAISS vector index."),
        new(".ggml", "GGML Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Legacy GGML model."),
        new(".h5", "Keras/HDF5 Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "TensorFlow/Keras model."),
        new(".hdf5", "HDF5 Model/Data", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "HDF5 ML data."),
        new(".hf", "Hugging Face Marker", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Hugging Face metadata marker."),
        new(".index", "Model/Vector Index", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "TF/checkpoint/vector index."),
        new(".keras", "Keras Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Native Keras model."),
        new(".llamafile", "Llamafile", "AI/Automation", "disabled", "high", "cm-editar.ai", null, "Llamafile packaged executable model."),
        new(".lora", "LoRA Adapter", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "LoRA adapter weights."),
        new(".loras", "LoRA Pack", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Local LoRA pack."),
        new(".metadata", "AI Metadata", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "AI model/workflow metadata."),
        new(".midjourney", "Midjourney Prompts", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Midjourney prompt set."),
        new(".model", "Generic Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Generic ML model artifact."),
        new(".modelcard", "Model Card", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Model documentation card."),
        new(".nemo", "NVIDIA NeMo Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "NVIDIA NeMo model."),
        new(".npz", "NumPy Compressed Array", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "NumPy compressed arrays."),
        new(".npy", "NumPy Array", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "NumPy array."),
        new(".ort", "ONNX Runtime Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "ONNX Runtime optimized model."),
        new(".pb", "TensorFlow Graph", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "TensorFlow protobuf graph."),
        new(".pbtxt", "TensorFlow Text Graph", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "TF text protobuf."),
        new(".pkl", "Pickle File", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Python pickle (executes on load)."),
        new(".pickle", "Pickle File (alt)", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Python pickle (alt)."),
        new(".prompty", "Prompty File", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Prompty prompt asset."),
        new(".sft", "SFT Dataset", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Supervised fine-tuning dataset."),
        new(".spm", "SentencePiece Model", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "SentencePiece tokenizer model."),
        new(".t5x", "T5X Checkpoint", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Google T5X training artifact."),
        new(".tflite", "TF Lite Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "TensorFlow Lite mobile model."),
        new(".tokenizer", "Tokenizer", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Generic tokenizer asset."),
        new(".tokens", "Token Data", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Token list/cache."),
        new(".trt", "TensorRT Engine", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "NVIDIA TensorRT engine."),
        new(".engine", "TensorRT Engine (alt)", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "TRT engine (alt extension)."),
        new(".vae", "VAE Model", "AI/Automation", "disabled", "warn", "cm-editar.ai", null, "Stable Diffusion VAE artifact."),
        new(".vec", "Vector Embeddings", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Vector embeddings file."),
        new(".vectors", "Vector Store", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Vector store artifact."),
        new(".parquet", "Parquet AI Dataset", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Parquet AI dataset (cross-listed)."),
        new(".tiktoken", "Tiktoken Encoder", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "OpenAI tiktoken encoder data."),
        new(".mcp", "MCP Server Config", "AI/Automation", "enabled", "rec", "cm-editar.ai", null, "Model Context Protocol server config."),

        // === System ===
        new(".(blank)", "Blank File (no extension)", "System", "enabled", "warn", "cm-editar.user", null, "Creates an extension-less file."),
        new(".csr", "Certificate Signing Request", "System", "enabled", "rec", "system", null, "X.509 cert signing request."),
        new(".clang-format", "Clang Format Config", "System", "enabled", "rec", "cm-editar.dev", null, "clang-format style config."),
        new(".editorconfig", "EditorConfig", "System", "enabled", "rec", "cm-editar.dev", null, "EditorConfig file."),
        new(".env", "Env Vars", "System", "enabled", "warn", "cm-editar.dev", null, "Dotenv environment file (may contain secrets)."),
        new(".eslintrc", "ESLint Config", "System", "enabled", "rec", "cm-editar.dev", null, "ESLint config."),
        new(".gitattributes", "Git Attributes", "System", "enabled", "rec", "cm-editar.dev", null, "Git attributes config."),
        new(".gitignore", "Git Ignore", "System", "enabled", "rec", "cm-editar.dev", null, "Git ignore patterns."),
        new(".gitmodules", "Git Submodules", "System", "enabled", "rec", "cm-editar.dev", null, "Git submodules config."),
        new(".htaccess", "Apache htaccess", "System", "enabled", "rec", "system", null, "Apache htaccess config."),
        new(".npmrc", "npm RC", "System", "enabled", "rec", "cm-editar.dev", null, "npm RC config."),
        new(".prettierrc", "Prettier Config", "System", "enabled", "rec", "cm-editar.dev", null, "Prettier config."),
    };
}
